version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-db
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/password  # Change password here
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 1G
    ports:
      - "7474:7474"   # HTTP Web Interface
      - "7687:7687"   # Bolt Protocol for Queries
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_conf:/var/lib/neo4j/conf

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_conf:
